// Bruitages : un prompt ElevenLabs (POST /v1/sound-generation) par événement sonore du jeu
// (`SfxId` de src/audio/sfx.ts, routés par src/audio/router.ts). Prompts en anglais (meilleure
// adhérence du modèle eleven_text_to_sound_v2) ; intention en français pour la bible.
//
// [id, intention (FR), prompt (EN), durée (s, ≥ 0,5), prises, traitement (FR), options]
// Options : keep ('synth' : la synthèse du jeu reste la référence, l'échantillon n'est qu'une couche
// facultative ; 'layer' : l'échantillon se superpose à la synthèse), validated (prise validée par le
// porteur du projet le 2026-10-09 : generation_id et flow ElevenLabs ; non régénérée), influence
// (prompt_influence, 0,3 par défaut : valeur validée par le porteur du projet), sample (lot d'écoute), pan ('spatial' | 'centre').
//
// Règles (bible § 2) : rien d'utile au-dessus de 9 kHz, pas de pic, attaques ≥ 2 ms, le télégraphe
// garde SA signature (bip montant), la rareté du loot se reconnaît à la hauteur et au timbre.

// Style de référence : les 4 prompts validés (impact, whistle, dash, loot4) : matière concrète,
// « close-mic, dry », durée dite dans le prompt, fin propre.
const S =
  'single isolated sound effect, close-mic, dry, no reverb, no music, no voice, no background ambience, clean ending, game audio';

export const SFX_FAMILIES = [
  {
    id: 'combat-heros',
    name: 'Combat du héros (clé à tire-fond)',
    default: {
      post: { hp: 60, lp: 9000, peak: -6 },
      treatment: 'HPF 60 Hz, LPF 9 kHz, compression 3:1 rapide, pan spatial',
    },
    items: [
      [
        'swing1',
        'Coup 1 « Serrage » : souffle montant de la clé lourde',
        `Heavy steel railway wrench swung fast through the air, short rising whoosh, ${S}`,
        0.5,
        4,
        'Bas-médium gardé, aigus doux',
      ],
      [
        'swing2',
        'Coup 2 « Desserrage » : souffle descendant',
        `Heavy steel wrench backhand swing, short falling whoosh with slight metal rattle, ${S}`,
        0.5,
        4,
        'Idem, pan légèrement opposé au coup 1',
      ],
      [
        'swing3',
        'Coup 3 « Tire-fond » : élan lourd, plus long',
        `Very heavy iron track wrench overhead swing, deep powerful whoosh building up, ${S}`,
        0.6,
        4,
        'Grave renforcé (+2 dB à 120 Hz)',
      ],
      [
        'swingDash',
        'Attaque de correspondance (estoc après dash)',
        `Fast forward thrust with a steel bar, sharp air cut, ${S}`,
        0.5,
        3,
        'Court, transitoire net',
      ],
      [
        'slam',
        'Coup 3 au sol : BONG métal sur rail, signature du jeu',
        `Heavy iron wrench slamming onto a steel railway rail, deep resonant metallic BONG with ballast gravel scatter, ${S}`,
        1.5,
        6,
        'Le son-signature : crête −4 dBFS, queue de 1 s, pas d’aigu strident',
        { sample: true, keep: 'layer' },
      ],
      [
        'impact',
        'Impact de la clé sur une cible (léger / lourd)',
        'Heavy steel wrench striking a laptop and a padded suit, punchy metallic clang with a short papery crunch, close-mic, dry, no reverb',
        0.5,
        6,
        'Deux familles de prises : légères et lourdes (amount)',
        { validated: { generationId: '05SgcLEGWcxffUllIZIY', flowId: 'Cd8ob8MfULDo8CQqtkQq' } },
      ],
      [
        'crit',
        'Critique : éclat brillant au-dessus de l’impact',
        `Bright metallic ring accent on a critical hit, short sparkle, not harsh, ${S}`,
        0.5,
        3,
        'LPF 7 kHz : brillant sans siffler',
      ],
      [
        'dash',
        'Dash « Retard » : souffle + crissement de frein doux',
        'Quick whoosh of a fast dodge followed by a short hiss of train air brakes releasing, snappy, half a second, close',
        0.5,
        4,
        'Crissement filtré passe-bas 3 kHz',
        { validated: { generationId: 'SkTygjpDBCFwPVG6e7Zh', flowId: 'vkRfsr0ZCyK9gvdtgk3E' } },
      ],
      [
        'perfectDash',
        'Dash parfait : carillon « +15 min »',
        `Short two-note railway station chime, bright and rewarding, slow-motion feel, ${S}`,
        0.8,
        3,
        'Centre, pas de pan',
      ],
      [
        'whistle',
        'Coup de sifflet du chef de gare',
        "Sharp station master's pea whistle, one piercing blast with a trill, slight echo of a large train station hall at night",
        0.8,
        3,
        'Passe-bas 3,4 kHz (accessibilité), crête −8 dBFS',
        { validated: { generationId: 'XiZBo4tizTqdt2Cipyqa', flowId: '7bQfLaPx6uQr9dBQBFzR' } },
      ],
      [
        'preavis',
        'Préavis de grève : long sifflet puis clameur qui gonfle',
        `Long railway guard whistle followed by a swelling crowd of workers cheering, megaphone feel, ${S}`,
        2.5,
        3,
        'Clameur sans mots intelligibles, LPF 6 kHz',
      ],
    ],
  },
  {
    id: 'impacts',
    name: 'Impacts, matières et KO',
    default: {
      post: { hp: 60, lp: 9000, peak: -6 },
      treatment: 'HPF 60 Hz, LPF 9 kHz, compression 3:1, pan spatial',
    },
    items: [
      [
        'hitPaper',
        'Consultant : liasse de papier qui vole',
        `Stack of office papers struck and scattering, crisp paper flutter, ${S}`,
        0.5,
        4,
        'Atténuer 4–6 kHz (−3 dB) : le papier est naturellement brillant',
      ],
      [
        'hitLaptop',
        'Coup lourd / Manager : portable qui claque et bipe',
        `Laptop lid slammed shut by a hit with a short error beep, plastic crack, ${S}`,
        0.6,
        3,
        'Bip court, jamais au-dessus de 2 kHz',
      ],
      [
        'hitMetal',
        'Borne automatique / Discosaure : carcasse de tôle',
        `Wrench hitting a hollow sheet-metal ticket kiosk, boomy metallic clang, ${S}`,
        0.6,
        3,
        'Grave résonant',
      ],
      [
        'hitDrone',
        'Drone : coque plastique + moteur qui hoquette',
        `Small plastic drone hit, hollow plastic knock and stuttering electric motor, ${S}`,
        0.6,
        3,
        'Moteur filtré',
      ],
      [
        'hitBoss',
        'Boss : costume épais et dossier',
        `Heavy blow on a thick wool suit and a ring binder, muffled thump with paper slap, ${S}`,
        0.6,
        4,
        'Grave, sans aigu',
      ],
      [
        'kill',
        'Ennemi vaincu « part en réunion » : pouf comique',
        `Comic soft deflating poof with a tiny office chair squeak, cartoonish but subtle, ${S}`,
        0.6,
        4,
        'Jamais violent, jamais organique',
      ],
      [
        'lastKill',
        'Dernier ennemi de la salle : carillon « ding-dong » de gare',
        `Classic two-tone railway station announcement chime ding-dong, warm, ${S}`,
        1.2,
        3,
        'Centre ; carillon de référence du jeu',
      ],
      [
        'wallSlam',
        'Ennemi plaqué contre un mur / quai',
        `Body slammed against a concrete platform wall, dull heavy thud, ${S}`,
        0.5,
        3,
        'Grave mat',
      ],
      [
        'explosion',
        'Explosion (Borne, objets) : souffle sourd sans débris tranchants',
        `Muffled cartoon explosion of a ticket machine, puff of smoke and scattering paper tickets, no sharp debris, ${S}`,
        1.5,
        3,
        'Compression douce, LPF 6 kHz',
      ],
      [
        'spawn',
        'Apparition d’un ennemi : glissement de badge',
        `Quick corporate badge swipe beep and soft whoosh arrival, ${S}`,
        0.5,
        3,
        'Discret, −10 dB sous les coups',
      ],
    ],
  },
  {
    id: 'etat-heros',
    name: 'Café, dégâts, Burnout, fin de Shift',
    default: {
      post: { hp: 50, lp: 9000, peak: -8 },
      treatment: 'HPF 50 Hz, LPF 9 kHz, centre (non spatial)',
    },
    items: [
      [
        'coffeeCup',
        'Gobelet sorti : plastique creux',
        `Plastic coffee cup pulled from a dispenser, hollow plastic click, ${S}`,
        0.5,
        3,
        'Centre',
      ],
      [
        'coffeeSip',
        'Gorgée : deux glouglous et une aspiration, puis « ah »',
        `Someone taking a hot sip of coffee from a plastic cup, two gulps and a satisfied breath, no words, ${S}`,
        1.2,
        4,
        'Centre, intime, proche du micro',
        { sample: true },
      ],
      [
        'hurt',
        'Le héros encaisse',
        `Dull body impact with cloth rustle, short, ${S}`,
        0.5,
        4,
        'Le grognement vient de la voix du héros (dialogues)',
      ],
      [
        'burnoutUp',
        'Palier de Burnout : tension qui monte',
        `Rising tense electrical hum swell with a heartbeat, short, ${S}`,
        1.5,
        2,
        'Nappe grave, pas de sifflement',
      ],
      [
        'meltdown',
        'Pétage de plombs : bourdonnement, crépitements, plomb qui saute',
        `Overloaded electrical fuse box buzzing and crackling, then a fuse blowing with a pop and power down, ${S}`,
        2.5,
        2,
        'Crête −8 dBFS, crépitements LPF 7 kHz',
      ],
      [
        'death',
        'Fin de Shift : « wah wah waaah » tendre, pas moqueur',
        `Sad muted trombone wah wah waah, gentle and tender, short, ${S}`,
        2,
        3,
        'Tendre : le joueur ne doit pas se sentir moqué',
      ],
      [
        'victory',
        'Shift tenu : fanfare de cuivres brève',
        `Short triumphant brass band fanfare sting, municipal brass band, warm, ${S}`,
        2.5,
        3,
        'Ré majeur si possible (cohérent avec l’OST)',
      ],
    ],
  },
  {
    id: 'ennemis',
    name: 'Ennemis : télégraphes et attaques',
    default: {
      post: { hp: 60, lp: 9000, peak: -8 },
      treatment: 'HPF 60 Hz, LPF 9 kHz, pan spatial',
    },
    items: [
      [
        'telegraph',
        'Télégraphe : bip montant (même code que le magenta)',
        `Short rising electronic warning beep, two notes ascending, clean sine-like tone, ${S}`,
        0.5,
        3,
        'RÈGLE : la synthèse du jeu reste la référence (hauteur fixe, grave pour boss et zones). L’échantillon ne doit jamais masquer le bip.',
        { sample: true, keep: 'synth', influence: 0.6 } /* signature à respecter à la lettre */,
      ],
      [
        'ticketFire',
        'Borne : imprimante à tickets + éjection',
        `Thermal ticket printer printing fast then ejecting a paper ticket, ${S}`,
        0.8,
        3,
        'Médium',
      ],
      [
        'ticketTear',
        'Ticket détruit par la clé : déchirure',
        `Paper ticket torn in half quickly, ${S}`,
        0.5,
        3,
        'Court',
      ],
      [
        'ticketThud',
        'Ticket qui s’écrase sur un mur',
        `Small paper ticket hitting a wall with a soft tap, ${S}`,
        0.5,
        2,
        'Très discret',
      ],
      [
        'droneShot',
        'Drone : tir de « laser qualité »',
        `Small drone firing a soft laser zap, toy-like, ${S}`,
        0.5,
        3,
        'LPF 6 kHz',
      ],
      [
        'droneDive',
        'Drone : piqué',
        `Small quadcopter drone diving fast with rising motor whine, ${S}`,
        0.8,
        3,
        'Whine filtré',
      ],
      [
        'droneScan',
        'Drone / spots du Discosaure : balayage de scan',
        `Electronic scanning sweep, soft rising and falling synth tone, ${S}`,
        1,
        2,
        'Doux',
      ],
      [
        'chrono',
        'Manager KPI : chronomètre tic-tac puis « ding »',
        `Mechanical stopwatch ticking four times then a small bell ding, ${S}`,
        1.5,
        2,
        'Le tic-tac doit être lisible en combat',
      ],
      [
        'tablet',
        'Tablette : swipe et tap',
        `Tablet screen swipe and double tap, ${S}`,
        0.5,
        2,
        'Discret',
      ],
      [
        'report',
        'Reporting : « ding-dong » de réunion visio',
        `Video conference join notification chime, corporate two-tone, ${S}`,
        0.8,
        2,
        'Centre',
      ],
      [
        'enemyMelee',
        'Coup de diaporama : glissement + clac de projecteur',
        `Slide projector advancing a slide with a clack, swoosh, ${S}`,
        0.5,
        3,
        'Médium',
      ],
      [
        'rush',
        'Quick win : ruée',
        `Fast footsteps dash on hard floor with a whoosh, ${S}`,
        0.6,
        3,
        'Pas courts',
      ],
      [
        'kpi',
        'Graphiques KPI : barres qui jaillissent',
        `Rising bar chart pop, three quick ascending digital blips, ${S}`,
        0.6,
        3,
        'Blips graves (pas de cri aigu)',
      ],
      [
        'kpiZap',
        'Laser / ligne KPI : zap',
        `Electric laser line zap, short buzzy sweep, ${S}`,
        0.6,
        3,
        'LPF 6 kHz',
      ],
    ],
  },
  {
    id: 'boss',
    name: 'Boss et ennemis majeurs',
    default: {
      post: { hp: 40, lp: 9000, peak: -6 },
      treatment: 'HPF 40 Hz, LPF 9 kHz, réverbération de salle courte, pan spatial',
    },
    items: [
      [
        'bossSweep',
        'Auditeur / Discosaure : balayage large',
        `Large heavy object swept in a wide arc, deep whoosh, ${S}`,
        0.8,
        3,
        'Grave',
      ],
      [
        'bossBarrier',
        'Auditeur : barrières de quai qui s’entrechoquent',
        `Metal crowd-control barriers clanging together, ${S}`,
        1,
        3,
        'Métal mat, pas strident',
      ],
      [
        'bossStamp',
        'Auditeur / Discosaure : tampon « Contrôle ! »',
        `Giant rubber stamp slammed on a desk, deep thud and rubber slap, ${S}`,
        0.8,
        3,
        'Grave, sub léger',
      ],
      [
        'bossLand',
        'Atterrissage lourd / émergence du Furet',
        `Heavy landing on a concrete railway platform, deep thump with gravel, ${S}`,
        0.8,
        3,
        'Sub contrôlé (HPF 40 Hz)',
      ],
      [
        'bossPhase',
        'Changement de phase : annonce de quai distordue + corne grave',
        `Distorted railway station PA chime followed by a deep low horn blast, ominous, ${S}`,
        2,
        2,
        'Centre ; crête −6 dBFS',
      ],
      [
        'ribbonSnip',
        'Ciseaux d’inauguration : deux claquements secs',
        `Giant ceremonial scissors cutting a ribbon, two crisp metallic snips, ${S}`,
        0.6,
        3,
        'Clairs mais LPF 8 kHz',
      ],
      [
        'stinkPuff',
        'Furet putride : bouffée de puanteur',
        `Low muffled gassy puff from a trash bag, comic and soft, ${S}`,
        0.8,
        3,
        'Grave étouffé',
      ],
      [
        'discoShimmer',
        'Boule à facettes : scintillement cristallin doux',
        `Soft glittering mirror ball shimmer, gentle chimes, ${S}`,
        1.5,
        2,
        'LPF 8 kHz, jamais strident (accessibilité)',
      ],
      [
        'fanfare',
        'Fanfare d’inauguration : accord de cuivres doux',
        `Short polite brass band chord for a ribbon-cutting ceremony, warm, ${S}`,
        2,
        2,
        'Centre',
      ],
    ],
  },
  {
    id: 'environnement',
    name: 'Zones, rames, portes et annonces',
    default: {
      post: { hp: 40, lp: 9000, peak: -6 },
      treatment: 'HPF 40 Hz, LPF 9 kHz, pan spatial',
    },
    items: [
      [
        'hazardThud',
        'Zone qui frappe / piétinement',
        `Heavy dull ground impact thud, ${S}`,
        0.5,
        3,
        'Grave',
      ],
      [
        'ringPulse',
        'Onde de choc annulaire',
        `Expanding shockwave pulse, deep whoomp with air ripple, ${S}`,
        0.8,
        3,
        'Sub contrôlé',
      ],
      [
        'train',
        'Rame qui traverse la voie : grondement, essieux, avertisseur deux tons',
        `Passenger train rushing through a station at speed, rumble, wheel clacks over rail joints and a two-tone horn, ${S}`,
        3,
        3,
        'Pan qui balaie de gauche à droite en post ; crête −6 dBFS',
        { sample: true },
      ],
      [
        'chime',
        'Annonce de gare : carillon à 3 notes (sans voix)',
        `Three-note railway station announcement chime, warm and clear, ${S}`,
        1.5,
        3,
        'Centre ; motif mélodique repris par l’OST',
      ],
      [
        'doorUnlock',
        'Salle nettoyée : verrou qui saute et deux notes de récompense',
        `Heavy door lock unlatching followed by two bright reward notes, ${S}`,
        1,
        3,
        'Centre',
      ],
      [
        'doorTaken',
        'Porte franchie : porte de service qui s’ouvre',
        `Industrial service door opening with a pneumatic hiss, ${S}`,
        0.8,
        2,
        'Centre',
      ],
    ],
  },
  {
    id: 'loot',
    name: 'Ramassages, choix et loot',
    default: {
      post: { hp: 80, lp: 9000, peak: -10 },
      treatment: 'HPF 80 Hz, LPF 9 kHz, pan spatial léger',
    },
    items: [
      [
        'pickupTickets',
        'Tickets ramassés',
        `Picking up a handful of paper tickets with a small coin-like jingle, ${S}`,
        0.5,
        3,
        'Court',
      ],
      [
        'pickupPs',
        'Points de Syndicalisme : tampon + note chaude',
        `Rubber stamp thump followed by a warm short reward note, ${S}`,
        0.6,
        2,
        'Chaud',
      ],
      [
        'pickupGrains',
        'Grains de café',
        `Coffee beans poured into a small tin, rattle, ${S}`,
        0.6,
        2,
        'Médium',
      ],
      [
        'pickupGobelet',
        'Gobelet ramassé',
        `Plastic cup picked up with a liquid slosh, ${S}`,
        0.5,
        2,
        'Court',
      ],
      [
        'pickupCornet',
        'Cornet de frites (Friterie)',
        `Paper cone of fries crinkling, ${S}`,
        0.5,
        2,
        'Court',
      ],
      [
        'pickupAvantage',
        'Avantage acquis : radio qui grésille + accord',
        `Walkie-talkie squelch followed by a bright short reward chord, ${S}`,
        1,
        2,
        'Centre',
      ],
      [
        'choice',
        'Fenêtre de choix d’Avantage',
        `Soft card-shuffle whoosh with a gentle magical shimmer, ${S}`,
        0.8,
        2,
        'Bus UI, centre',
      ],
      [
        'loot0',
        'Loot Réformé : clinquant modeste',
        `Small cheap metal item dropping on concrete, dull clink, ${S}`,
        0.5,
        2,
        'Le plus grave et le plus mat',
      ],
      [
        'loot1',
        'Loot Réglementaire',
        `Metal tool dropping on concrete with a clean clink, ${S}`,
        0.6,
        2,
        '+2 demi-tons',
      ],
      [
        'loot2',
        'Loot Homologué : tintement brillant',
        `Quality tool dropping with a bright bell-like ping, ${S}`,
        0.8,
        2,
        '+4 demi-tons',
      ],
      [
        'loot3',
        'Loot Hors-série : carillon + scintillement',
        `Rare item drop, glassy chime with soft sparkle, ${S}`,
        1.2,
        2,
        '+7 demi-tons',
      ],
      [
        'loot4',
        'Loot Patrimoine : carillon cuivré, faisceau',
        'Video game loot drop sting for a legendary item: a heavy brass object lands on concrete with a solid thud, followed by a short warm bell shimmer and a soft reverse-cymbal tail; retro train-station atmosphere, slightly dusty, 1.5 seconds, clean ending',
        1.5,
        3,
        'Le son le plus « riche » du loot ; crête −6 dBFS',
        { validated: { generationId: 'Uu6mU4EptZKYtyOv1G5Z', flowId: 'EX35CECmDw3jkNZ5ygcY' } },
      ],
      [
        'lootEquip',
        'Équiper : sangle + mousqueton',
        `Leather strap buckle and metal carabiner click, ${S}`,
        0.6,
        2,
        'Centre',
      ],
      [
        'lootBag',
        'Mettre au sac : tissu + zip',
        `Fabric rustle and short zipper close, ${S}`,
        0.6,
        2,
        'Centre',
      ],
      [
        'lootScrap',
        'Ferraille : pièces dans un bac',
        `Scrap metal pieces dropped into a metal bin, ${S}`,
        0.8,
        2,
        'Médium',
      ],
    ],
  },
  {
    id: 'ui',
    name: 'Interface',
    default: {
      post: { hp: 120, lp: 8000, peak: -14 },
      treatment: 'HPF 120 Hz, LPF 8 kHz, bus UI, centre, très bas',
    },
    items: [
      [
        'uiHover',
        'Survol',
        `Very soft tiny UI tick, ${S}`,
        0.5,
        2,
        'La synthèse reste la référence',
        { keep: 'synth' },
      ],
      [
        'uiClick',
        'Clic',
        `Soft clicky button press like a vintage railway switch, ${S}`,
        0.5,
        2,
        'Interrupteur de pupitre',
      ],
      [
        'uiOpen',
        'Ouverture de menu',
        `Soft whoosh with two gentle ascending notes, ${S}`,
        0.6,
        2,
        'Centre',
      ],
    ],
  },
];

/** Ambiances en boucle (loop: true, 30 s, à jouer sur le bus ambience). */
export const AMBIENCES = [
  [
    'amb.quai-nuit',
    'Quai de nuit (biome 1, roulement Nuit)',
    'Empty railway platform at night, low electrical hum of sodium lamps, buzzing neon tube, distant train rumble, faint gravel ballast and dripping water, light wind, no voices, seamless loop',
    30,
    2,
  ],
  [
    'amb.quai-matin',
    'Quai au matin (brouillard, drones)',
    'Foggy railway platform at dawn, cold air, distant commuter murmurs without words, far drone propellers, birds, seamless loop',
    30,
    1,
  ],
  [
    'amb.hall',
    'Hall historique (biome 3, RDC)',
    'Large historic train station hall, big reverberant space, distant footsteps, wooden benches creaking, muffled departures board clicks, no intelligible voices, seamless loop',
    30,
    2,
  ],
  [
    'amb.passerelle',
    'Passerelle en hauteur (biome 2)',
    'High glass and steel footbridge above railway tracks at dawn, strong whistling wind, cables creaking, trains passing far below, pigeons cooing, seamless loop',
    30,
    2,
  ],
  [
    'amb.cour-bag',
    'Cour intérieure du BAG (hub, extérieur)',
    'Inner courtyard of an office building at night, distant city traffic, ventilation units humming, a pigeon, rain drips from gutters, seamless loop',
    30,
    1,
  ],
  [
    'amb.occ',
    'Salle des opérations (OCC) : radio, cafetière',
    'Small cozy railway operations control room at night, quiet radio chatter with unintelligible words, old coffee machine gurgling and hissing, computer fans, clock ticking, seamless loop',
    30,
    2,
  ],
  [
    'amb.poubelles',
    'Coin poubelles (antre du Furet)',
    'Back alley trash corner at night, buzzing flies, plastic bags rustling in the wind, dripping pipe, distant rat squeaks, seamless loop',
    30,
    1,
  ],
  [
    'amb.open-space',
    'Open-space du BAG (biome 3, étages)',
    'Empty corporate open-plan office at night, air conditioning hum, printer warming up, fluorescent lights buzzing, elevator ding far away, seamless loop',
    30,
    1,
  ],
  [
    'amb.salle-conseil',
    'Salle du Conseil (arène finale)',
    'Large boardroom, deep ventilation drone, video conference speaker hiss, giant photocopier idling, tense, seamless loop',
    30,
    1,
  ],
];

/** Ponctuels d'ambiance (déclenchés au hasard par le directeur d'ambiance). */
export const AMBIENT_ONESHOTS = [
  [
    'amb1.cafetiere',
    'La Vieille Dame (cafetière de 1987) gargouille',
    'Old 1980s filter coffee machine gurgling and bubbling then hissing steam',
    4,
    3,
  ],
  [
    'amb1.radio',
    'Radio de bureau qui crachote',
    'Office two-way radio squelch and short static crackle, no words',
    1.5,
    3,
  ],
  [
    'amb1.rame-lointaine',
    'Rame qui passe au loin',
    'Distant freight train passing far away, low rumble and rail joint clacks fading',
    8,
    2,
  ],
  [
    'amb1.clac-rail',
    'Joint de rail « clac-clac »',
    'Two pairs of distant train wheel clacks over a rail joint',
    1.5,
    2,
  ],
  ['amb1.pigeon', 'Matricule 4412 (pigeon)', 'Single pigeon cooing and fluttering wings', 2, 2],
  [
    'amb1.neon',
    'Néon qui grésille',
    'Fluorescent neon tube flickering and buzzing briefly',
    1.5,
    3,
  ],
  [
    'amb1.escalator',
    'Escalator qui redémarre (un jour sur trois)',
    'Old escalator motor starting with a groan and steady mechanical rattle',
    4,
    1,
  ],
];
