/**
 * Source unique des chiffres d'équilibrage (transposition de docs/GDD.md § 13, sections 4 à 9).
 * Toute modification d'équilibrage se fait ici, jamais dans une scène ni dans un système.
 *
 * Écarts volontaires avec l'annexe du GDD :
 * - les clés de pause sont les valeurs de `Shift` (`morning` / `afternoon` / `night`)
 *   au lieu de `MATIN` / `APREM` / `NUIT`, pour n'avoir qu'un seul vocabulaire dans le code ;
 * - les identifiants de paliers de Fatigue sont en minuscules (`frais`, `burn-out`…).
 *
 * Unités : les minutes de l'horloge sont absolues depuis lundi 00:00 (jour 0) ;
 * 1 jour = 1440 min. Les pourcentages sont en points (5 = 5 %), les multiplicateurs en facteur.
 */
export const BALANCE = {
  clock: {
    /** Minutes in-game écoulées par seconde réelle en exploration (1 min toutes les 8 s). */
    CLOCK_MIN_PER_REAL_SEC: 0.125,
    /** Début de chaque pause, en minute du jour. */
    PAUSE_START: { morning: 360, afternoon: 840, night: 1320 },
    /** Signature du contrat : mardi 05:00 (jour 1). */
    BOSS_MINUTE: 1440 + 300,
    /** Heure de départ de chaque acte (absolue) : 4h47 (prologue), 14h00, 22h00 le lundi. */
    ACT_START_MINUTE: { 1: 287, 2: 840, 3: 1320 },
    /** Butée de relève (absolue) : 13h45 et 21h45. L'acte III n'a pas de butée (boss à 5h00). */
    OVERTIME_CAP: { 1: 825, 2: 1305 },
    /** Coûts fixes en minutes in-game. */
    COST_MIN: { combat: 10, zoneChange: 5, fastTravel: 15, nap: 120, occCoffee: 10, bagNap: 120 },
  },
  fatigue: {
    MAX: 100,
    START: 20,
    OVERTIME_MULT: 1.5,
    /** Plancher du produit des multiplicateurs de temps (Thermos, Lungo…). */
    TIME_MULT_FLOOR: 0.5,
    PER_HOUR: { morning: 2, afternoon: 3, night: 5 },
    COMBAT_BASE: 2,
    PER_3_ROUNDS: 1,
    FLEE: 5,
    CAFFEINE_CRASH: 5,
    BOSS_PER_ROUND: 1,
    COLLAPSE_RESET: 90,
    DEFEAT_SET: 50,
    /** Paliers contigus de 0 à 100 (vérifié par les tests). */
    tiers: [
      {
        id: 'frais',
        label: 'Frais',
        min: 0,
        max: 39,
        acc: 5,
        dmg: 1.0,
        init: 1.0,
        peRegen: 3,
        crit: 0,
        statusRes: 0,
        burnoutExtra: 0,
      },
      {
        id: 'fatigue',
        label: 'Fatigué',
        min: 40,
        max: 69,
        acc: 0,
        dmg: 0.95,
        init: 0.95,
        peRegen: 2,
        crit: 0,
        statusRes: 0,
        burnoutExtra: 0,
      },
      {
        id: 'epuise',
        label: 'Épuisé',
        min: 70,
        max: 89,
        acc: -10,
        dmg: 0.85,
        init: 0.85,
        peRegen: 1,
        crit: 5,
        statusRes: 0,
        burnoutExtra: 1,
      },
      {
        id: 'burn-out',
        label: 'Burn-out',
        min: 90,
        max: 99,
        acc: -20,
        dmg: 0.75,
        init: 0.7,
        peRegen: 0,
        crit: 10,
        statusRes: -20,
        burnoutExtra: 1,
      },
      {
        id: 'effondre',
        label: 'Effondré',
        min: 100,
        max: 100,
        acc: -20,
        dmg: 0.75,
        init: 0.7,
        peRegen: 0,
        crit: 0,
        statusRes: -20,
        burnoutExtra: 1,
      },
    ],
    recovery: {
      /** Café gratuit de l'OCC selon le niveau de la machine (1, 2, 3). */
      OCC_COFFEE: [30, 45, 60],
      MORNING_COFFEE_BONUS: 10,
      RELEVE_14H: 30,
      VEILLEE_22H: 50,
      GHOST_HOUSE_BONUS: 10,
      NAP: 40,
      GOBELET: 20,
      PREMIUM_COFFEE: 20,
      PREMIUM_COFFEE_MAX: 3,
      /** Tasse de Relève « Ristretto » : Fatigue −10 au moment du choix (GDD § 4.5). */
      RISTRETTO: 10,
    },
    timeMult: { thermos: 0.8, lungo: 0.75 },
  },
  pause: {
    morning: {
      enemyStatMult: 1.0,
      xpMult: 1.0,
      ticketMult: 1.0,
      critBonus: 0,
      accBonus: 5,
      defMult: 1.0,
      groups: [3, 4],
      groupSize: [1, 3],
      aiAttackWeight: 0.6,
    },
    afternoon: {
      enemyStatMult: 1.1,
      xpMult: 1.0,
      ticketMult: 1.2,
      critBonus: 0,
      accBonus: 0,
      defMult: 1.1,
      groups: [2, 3],
      groupSize: [2, 4],
      aiAttackWeight: 0.6,
    },
    night: {
      enemyStatMult: 1.2,
      xpMult: 1.25,
      ticketMult: 1.5,
      critBonus: 10,
      accBonus: 0,
      defMult: 1.0,
      groups: [1, 2],
      groupSize: [1, 3],
      aiAttackWeight: 0.8,
    },
  },
  combat: {
    INIT_RANDOM: 5,
    BASE_HIT: 90,
    HIT_MIN: 30,
    HIT_MAX: 99,
    CRIT_BASE: 5,
    CRIT_CAP: 50,
    CRIT_MULT: 1.5,
    CRIT_PER_MORAL: 10,
    ATK_MULT: 2,
    DEF_MULT: 1,
    VARIANCE_MIN: 0.9,
    VARIANCE_RANGE: 0.2,
    DEFEND_MULT: 0.5,
    SHIELD_MULT: 0.5,
    WEAKNESS_MULT: 2,
    SYNDIQUE_DEF: 1.3,
    TARIF_REDUIT_DEF: 0.7,
    FLEE_BASE: 50,
    FLEE_PER_SPEED: 3,
    FLEE_MIN: 10,
    FLEE_MAX: 90,
    STATUS_CHANCE_MIN: 5,
    STATUS_CHANCE_MAX: 95,
    HERO_RES_CAP: 50,
    ENEMY_RES: { normal: 10, elite: 30, boss: 50 },
    DODGE: { consultant: 15 },
  },
  status: {
    CAFEINE: { turns: 3, speedMult: 1.25, acc: 10, sleepImmune: true },
    SYNDIQUE: { turns: 3, defMult: 1.3 },
    DEMOTIVE: { turns: 3, dmgMult: 0.75, moralPenalty: 30 },
    BLOQUE: { turns: 1, immunityTurns: 1 },
    BURNOUT: { turns: 3, hpLossPct: 0.06 },
    CONFUSION: { turns: 2, misdirectChance: 0.4 },
    SOMMEIL: { maxTurns: 2, wakeOnDamage: true },
    DECALAGE: { turns: 3, acc: -10, initMult: 0.8 },
  },
  progression: {
    MAX_LEVEL: 20,
    XP_BASE: 40,
    XP_EXP: 1.5,
    /** [valeur au niveau 1, gain par niveau] */
    HERO: { hp: [60, 12], pe: [20, 3], force: [10, 2], def: [8, 1.5], speed: [10, 1] },
    /** [pv, force, déf, vit] relatifs au héros */
    ALLY_COEF: {
      josiane: [1.3, 0.8, 1.4, 0.8],
      rudy: [1.0, 0.9, 1.0, 1.2],
      bene: [0.9, 0.8, 0.9, 1.1],
      yasmina: [0.85, 1.0, 0.85, 1.15],
      kevin: [1.1, 1.3, 1.0, 0.9],
      fatou: [0.9, 0.6, 1.0, 1.0],
    },
    QUEST_XP: { 1: 50, 2: 150, 3: 300 },
  },
  enemies: {
    STAT_FORMULA: { hp: [20, 12], force: [6, 2], def: [4, 1.3], speed: [8, 1] },
    /** [pv, force, déf, vit] */
    ARCHETYPES: {
      consultant: [0.8, 1.0, 0.8, 1.3],
      managerKpi: [1.4, 0.9, 1.4, 0.8],
      coachAgile: [0.9, 0.7, 1.0, 1.1],
      reorganisateurRh: [2.5, 1.1, 1.2, 1.0],
      boss: [1.0, 1.3, 1.3, 1.0],
    },
    XP: { base: 10, coef: 6, exp: 1.5, typeMult: { normal: 1, elite: 2.5, boss: 6 } },
    TICKETS: { perLevel: 3, eliteMult: 3 },
    REFERENCE_LEVEL: { 1: 4, 2: 10, 3: 17 },
    CONSULTANT_SUMMON_ROUND: 3,
    MANAGER_FORCE_PER_ROUND: 0.05,
    MANAGER_FORCE_CAP: 0.5,
    REPORTING_EVERY: 3,
  },
  boss: {
    LEVEL: 20,
    SIGNATURE_COUNTER: 10,
    SIGNATURE_MIN_IF_LATE: 6,
    LATE_STEP_MIN: 30,
    PROOF_PUSHBACK: 3,
    PROOF_MORAL: 5,
    PHASE_HP: [1000, 1200, 900],
    CLAUSE_HP: 200,
    CLAUSE_DEF: 30,
    CLAUSE_EXTRA_TICK_EVERY: 3,
    PHASE3_MORAL_BELOW: 40,
    CONCRETE_QUESTION_POWER: 250,
    COST_CUTTING_MORAL: -3,
    EARLY_WAIT_FATIGUE_MULT: 0.5,
  },
  moral: {
    START: 10,
    MAX: 100,
    GOOD_ENDING_MIN: 60,
    GENERAL_STRIKE_MIN: 80,
    gains: {
      recruitAlly: 5,
      actOneBoss: 5,
      fragment: 2,
      jeanMiDelivered: 5,
      jeanMiSpared: -10,
      jeanMiRedemption: 15,
      ghostQuest: 10,
      lumeconQuest: 10,
      sideQuest: 3,
      serviceNote: 1,
      allNotesBonus: 3,
      crinPorteBonheur: 2,
      noirVieilleDame: 5,
      defeat: -5,
      endDemotivated: -1,
    },
  },
  economy: {
    DEFEAT_TICKET_LOSS: 0.25,
    NIGHT_VENDING_MULT: 1.5,
    PAYROLL_PER_ACT: 30,
    STACK_MAX: 9,
    BEANS_DROP_CHANCE: 0.2,
    BEANS_DROP: [1, 3],
    ELITE_BEANS: [3, 5],
    DROPS: { postIt: 0.4, agrafeuse: 0.25, cleUsb: 0.08, cleUsbElite: 0.5 },
    MACHINE_UPGRADES: [
      { level: 2, beans: 15, tickets: 150 },
      { level: 3, beans: 40, tickets: 500 },
    ],
    GOBELETS_PER_PAUSE: [1, 2, 3],
    TIREFOND: [
      { rank: 0, force: 4, crit: 0, tickets: 0, agrafeuses: 0, cleUsb: 0 },
      { rank: 1, force: 10, crit: 0, tickets: 150, agrafeuses: 5, cleUsb: 0 },
      { rank: 2, force: 18, crit: 5, tickets: 450, agrafeuses: 12, cleUsb: 2 },
      { rank: 3, force: 28, crit: 10, tickets: 1000, agrafeuses: 20, cleUsb: 5 },
    ],
  },
} as const;

export type FatigueTier = (typeof BALANCE.fatigue.tiers)[number];
export type FatigueTierId = FatigueTier['id'];
export type ActNumber = keyof typeof BALANCE.clock.ACT_START_MINUTE;
export type MachineLevel = 1 | 2 | 3;
