/**
 * Index des fichiers audio du jeu (public/audio). FICHIER GÉNÉRÉ par
 * `node tools/audio/build-web-audio.mjs` : ne pas modifier à la main.
 *
 * - Musique : OST, prise retenue t1, WebM/Opus 96 kb/s, silences de tête et de queue retirés.
 *   `loopEnd` : fin du dernier passage plein (s), le fondu enchaîné de la boucle se termine là.
 * - Voix : WebM/Opus 64 kb/s mono. `file: null` : réplique pas encore enregistrée (sous-titre seul).
 * Poids : musique 18.60 Mo, voix 3.23 Mo.
 */

export interface MusicFile {
  readonly file: string;
  readonly duration: number;
  readonly loopEnd: number;
  readonly bytes: number;
}

export interface VoiceLineFile {
  readonly id: string;
  readonly voice: 'leon' | 'yasmina' | 'invite' | 'lurcke' | 'marcel' | 'josiane' | 'bene';
  readonly file: string | null;
  /** Texte du catalogue sans les balises d'émotion. */
  readonly subtitle: string;
  /** Réplique inventée (l'Invité d'honneur) : l'UI affiche « réplique fictive ». */
  readonly fictive: boolean;
}

export const MUSIC_FILES = {
  'ost.01-prise-de-poste': {
    file: 'music/01-prise-de-poste.webm',
    duration: 103.51,
    loopEnd: 99.41,
    bytes: 1467954,
  },
  'ost.02-occ-jour': {
    file: 'music/02-occ-jour.webm',
    duration: 121.33,
    loopEnd: 117.41,
    bytes: 1709675,
  },
  'ost.03-occ-nuit': {
    file: 'music/03-occ-nuit.webm',
    duration: 115.98,
    loopEnd: 109.91,
    bytes: 1544753,
  },
  'ost.04-quais-exploration': {
    file: 'music/04-quais-exploration.webm',
    duration: 117.56,
    loopEnd: 113.91,
    bytes: 1459017,
  },
  'ost.05-quais-combat': {
    file: 'music/05-quais-combat.webm',
    duration: 113.3,
    loopEnd: 107.91,
    bytes: 1381106,
  },
  'ost.06-passerelle': {
    file: 'music/06-passerelle.webm',
    duration: 88.53,
    loopEnd: 83.61,
    bytes: 1143037,
  },
  'ost.07-hall-bag': {
    file: 'music/07-hall-bag.webm',
    duration: 96.21,
    loopEnd: 94.01,
    bytes: 1262256,
  },
  'ost.08-boss-auditeur': {
    file: 'music/08-boss-auditeur.webm',
    duration: 89.62,
    loopEnd: 87.81,
    bytes: 1182010,
  },
  'ost.09-boss-invite': {
    file: 'music/09-boss-invite.webm',
    duration: 89.54,
    loopEnd: 88.41,
    bytes: 1158337,
  },
  'ost.10-boss-discosaure': {
    file: 'music/10-boss-discosaure.webm',
    duration: 90.09,
    loopEnd: 88.81,
    bytes: 1093544,
  },
  'ost.11-boss-lurcke': {
    file: 'music/11-boss-lurcke.webm',
    duration: 119.06,
    loopEnd: 116.21,
    bytes: 1558827,
  },
  'ost.12-departs-victoire': {
    file: 'music/12-departs-victoire.webm',
    duration: 61.62,
    loopEnd: 57.51,
    bytes: 789479,
  },
  'ost.13-departs-supprime': {
    file: 'music/13-departs-supprime.webm',
    duration: 26.81,
    loopEnd: 24.31,
    bytes: 421956,
  },
  'ost.14-le-7h12': {
    file: 'music/14-le-7h12.webm',
    duration: 178.03,
    loopEnd: 169.81,
    bytes: 2424655,
  },
} as const satisfies Record<string, MusicFile>;

export type MusicFileId = keyof typeof MUSIC_FILES;

export const VOICE_FILES: readonly VoiceLineFile[] = [
  {
    id: 'vo.leon.effort.coup1',
    voice: 'leon',
    file: 'vo/leon/leon.effort.coup1.webm',
    subtitle: 'Hm !',
    fictive: false,
  },
  {
    id: 'vo.leon.effort.coup2',
    voice: 'leon',
    file: 'vo/leon/leon.effort.coup2.webm',
    subtitle: 'Hah !',
    fictive: false,
  },
  {
    id: 'vo.leon.effort.coup3',
    voice: 'leon',
    file: 'vo/leon/leon.effort.coup3.webm',
    subtitle: 'Hnnh… HA !',
    fictive: false,
  },
  {
    id: 'vo.leon.effort.dash',
    voice: 'leon',
    file: 'vo/leon/leon.effort.dash.webm',
    subtitle: 'Hup !',
    fictive: false,
  },
  {
    id: 'vo.leon.effort.sifflet',
    voice: 'leon',
    file: 'vo/leon/leon.effort.sifflet.webm',
    subtitle: 'Tout le monde… dehors !',
    fictive: false,
  },
  {
    id: 'vo.leon.effort.preavis',
    voice: 'leon',
    file: 'vo/leon/leon.effort.preavis.webm',
    subtitle: 'Préavis déposé !',
    fictive: false,
  },
  {
    id: 'vo.leon.douleur.legere',
    voice: 'leon',
    file: 'vo/leon/leon.douleur.legere.webm',
    subtitle: 'Ah…',
    fictive: false,
  },
  {
    id: 'vo.leon.douleur.lourde',
    voice: 'leon',
    file: 'vo/leon/leon.douleur.lourde.webm',
    subtitle: 'Aïe… ça, c’était pas au planning.',
    fictive: false,
  },
  {
    id: 'vo.leon.ko',
    voice: 'leon',
    file: 'vo/leon/leon.ko.webm',
    subtitle: '… Fin de service.',
    fictive: false,
  },
  {
    id: 'vo.leon.cafe',
    voice: 'leon',
    file: 'vo/leon/leon.cafe.webm',
    subtitle: 'Ah. Voilà.',
    fictive: false,
  },
  {
    id: 'vo.leon.soupir',
    voice: 'leon',
    file: 'vo/leon/leon.soupir.webm',
    subtitle: '…',
    fictive: false,
  },
  {
    id: 'vo.leon.bark.debut',
    voice: 'leon',
    file: 'vo/leon/leon.bark.debut.webm',
    subtitle: 'Bon. On y va.',
    fictive: false,
  },
  {
    id: 'vo.leon.bark.salle',
    voice: 'leon',
    file: 'vo/leon/leon.bark.salle.webm',
    subtitle: 'Salle tenue.',
    fictive: false,
  },
  {
    id: 'vo.leon.bark.energie',
    voice: 'leon',
    file: 'vo/leon/leon.bark.energie.webm',
    subtitle: 'Faut que je boive un café.',
    fictive: false,
  },
  {
    id: 'vo.leon.bark.burnout',
    voice: 'leon',
    file: 'vo/leon/leon.bark.burnout.webm',
    subtitle: 'Je suis en pause, là.',
    fictive: false,
  },
  {
    id: 'vo.leon.bark.petage',
    voice: 'leon',
    file: 'vo/leon/leon.bark.petage.webm',
    subtitle: 'Ça suffit !',
    fictive: false,
  },
  {
    id: 'vo.leon.bark.loot',
    voice: 'leon',
    file: 'vo/leon/leon.bark.loot.webm',
    subtitle: 'Ça, c’est du patrimoine.',
    fictive: false,
  },
  {
    id: 'vo.leon.bark.dashparfait',
    voice: 'leon',
    file: 'vo/leon/leon.bark.dashparfait.webm',
    subtitle: 'Retard indépendant de ma volonté.',
    fictive: false,
  },
  {
    id: 'vo.leon.bark.consultant',
    voice: 'leon',
    file: 'vo/leon/leon.bark.consultant.webm',
    subtitle: 'Votre titre de transport, s’il vous plaît.',
    fictive: false,
  },
  {
    id: 'vo.leon.boss.signature',
    voice: 'leon',
    file: 'vo/leon/leon.boss.signature.webm',
    subtitle: 'On vient arrêter la signature.',
    fictive: false,
  },
  {
    id: 'vo.leon.boss.article47',
    voice: 'leon',
    file: 'vo/leon/leon.boss.article47.webm',
    subtitle: 'Article quarante-sept, alinéa trois : préavis de sept jours.',
    fictive: false,
  },
  {
    id: 'vo.leon.boss.preuve',
    voice: 'leon',
    file: 'vo/leon/leon.boss.preuve.webm',
    subtitle: 'Ceci a été présenté au comité. Ceci n’a jamais été montré au terrain.',
    fictive: false,
  },
  {
    id: 'vo.leon.boss.question',
    voice: 'leon',
    file: 'vo/leon/leon.boss.question.webm',
    subtitle: 'Mais concrètement… sur le terrain, ça donne quoi ?',
    fictive: false,
  },
  {
    id: 'vo.marcel.hub.01',
    voice: 'marcel',
    file: 'vo/marcel/marcel.hub.01.webm',
    subtitle:
      'De mon temps, le retard, on l’appelait l’aventure. Maintenant, ils l’appellent un KPI.',
    fictive: false,
  },
  {
    id: 'vo.marcel.hub.02',
    voice: 'marcel',
    file: 'vo/marcel/marcel.hub.02.webm',
    subtitle: 'Le Tableau des revendications, fieu. Chaque PS, c’est un acquis.',
    fictive: false,
  },
  {
    id: 'vo.marcel.hub.03',
    voice: 'marcel',
    file: 'vo/marcel/marcel.hub.03.webm',
    subtitle: 'Ça va, fieu ? T’as eu une aventure courte. Allez, une tasse et on y retourne.',
    fictive: false,
  },
  {
    id: 'vo.marcel.hub.04',
    voice: 'marcel',
    file: 'vo/marcel/marcel.hub.04.webm',
    subtitle: 'Ils ont reprogrammé ? Bien. Tant qu’ils reprogramment, on existe.',
    fictive: false,
  },
  {
    id: 'vo.marcel.hub.05',
    voice: 'marcel',
    file: 'vo/marcel/marcel.hub.05.webm',
    subtitle:
      'Battu par un gamin en baskets blanches ? De mon temps, ils avaient au moins des chaussures.',
    fictive: false,
  },
  {
    id: 'vo.marcel.hub.06',
    voice: 'marcel',
    file: 'vo/marcel/marcel.hub.06.webm',
    subtitle:
      'Il a signé ? … Non. Regarde l’écran : reprogrammé. Le Sondage est de notre côté, fieu. Pour l’instant.',
    fictive: false,
  },
  {
    id: 'vo.marcel.radio.01',
    voice: 'marcel',
    file: 'vo/marcel/marcel.radio.01.webm',
    subtitle: 'De mon temps, on inaugurait les gares. Pas leur vente.',
    fictive: false,
  },
  {
    id: 'vo.marcel.hub.07',
    voice: 'marcel',
    file: 'vo/marcel/marcel.hub.07.webm',
    subtitle: 'Tant que je respire, la porte s’ouvre.',
    fictive: false,
  },
  {
    id: 'vo.marcel.radio.02',
    voice: 'marcel',
    file: 'vo/marcel/marcel.radio.02.webm',
    subtitle: 'De mon temps, on frappait d’abord. Tiens.',
    fictive: false,
  },
  {
    id: 'vo.marcel.hub.08',
    voice: 'marcel',
    file: 'vo/marcel/marcel.hub.08.webm',
    subtitle: 'Assieds-toi deux minutes. Le Sondage attendra. Il attend toujours.',
    fictive: false,
  },
  {
    id: 'vo.yasmina.hub.01',
    voice: 'yasmina',
    file: 'vo/yasmina/yasmina.hub.01.webm',
    subtitle:
      'Roulement de nuit. Moins de monde, plus de cadres. Je te mets le biome un en orange.',
    fictive: false,
  },
  {
    id: 'vo.yasmina.hub.02',
    voice: 'yasmina',
    file: 'vo/yasmina/yasmina.hub.02.webm',
    subtitle:
      'Incident voyageur sur ta ligne. Toi. Je te mets en voie d’attente, le temps de te recoller.',
    fictive: false,
  },
  {
    id: 'vo.yasmina.hub.03',
    voice: 'yasmina',
    file: 'vo/yasmina/yasmina.hub.03.webm',
    subtitle: 'L’Auditeur est en voie d’attente. Définitive, j’espère.',
    fictive: false,
  },
  {
    id: 'vo.yasmina.radio.01',
    voice: 'yasmina',
    file: 'vo/yasmina/yasmina.radio.01.webm',
    subtitle:
      'Retard indépendant de ta volonté. Quinze minutes. Joli. Je l’inscris au registre des excuses.',
    fictive: false,
  },
  {
    id: 'vo.yasmina.radio.02',
    voice: 'yasmina',
    file: 'vo/yasmina/yasmina.radio.02.webm',
    subtitle: 'Départ autorisé. Voie libre jusqu’au quai trois.',
    fictive: false,
  },
  {
    id: 'vo.yasmina.radio.03',
    voice: 'yasmina',
    file: 'vo/yasmina/yasmina.radio.03.webm',
    subtitle: 'Passerelle. Vent de face. Ne regarde pas en bas.',
    fictive: false,
  },
  {
    id: 'vo.yasmina.radio.04',
    voice: 'yasmina',
    file: 'vo/yasmina/yasmina.radio.04.webm',
    subtitle: 'Hall et BAG. À partir d’ici, plus de réseau. Sauf moi.',
    fictive: false,
  },
  {
    id: 'vo.yasmina.radio.05',
    voice: 'yasmina',
    file: 'vo/yasmina/yasmina.radio.05.webm',
    subtitle: 'Signal fermé devant. Le boss t’attend. Je reste en ligne.',
    fictive: false,
  },
  {
    id: 'vo.yasmina.radio.06',
    voice: 'yasmina',
    file: 'vo/yasmina/yasmina.radio.06.webm',
    subtitle: 'Mobilisation à cent. Tu peux déposer ton préavis.',
    fictive: false,
  },
  {
    id: 'vo.yasmina.radio.07',
    voice: 'yasmina',
    file: 'vo/yasmina/yasmina.radio.07.webm',
    subtitle: 'Plus de Gobelets. Je te trouve une salle café.',
    fictive: false,
  },
  {
    id: 'vo.yasmina.radio.08',
    voice: 'yasmina',
    file: 'vo/yasmina/yasmina.radio.08.webm',
    subtitle: 'Shift tenu. Je te mets tout le réseau en vert.',
    fictive: false,
  },
  {
    id: 'vo.yasmina.hub.04',
    voice: 'yasmina',
    file: 'vo/yasmina/yasmina.hub.04.webm',
    subtitle: 'Quand je dis départ, tout le monde part.',
    fictive: false,
  },
  {
    id: 'vo.bene.hub.01',
    voice: 'bene',
    file: 'vo/bene/bene.hub.01.webm',
    subtitle:
      'Le Règlement, page trois cent douze : un consultant n’a pas de titre de transport. Je dis ça, je dis rien.',
    fictive: false,
  },
  {
    id: 'vo.bene.hub.02',
    voice: 'bene',
    file: 'vo/bene/bene.hub.02.webm',
    subtitle: 'Numéro suivant !',
    fictive: false,
  },
  {
    id: 'vo.bene.hub.03',
    voice: 'bene',
    file: 'vo/bene/bene.hub.03.webm',
    subtitle:
      'Elle t’a imprimé, la borne ? On ne négocie pas avec ces machines-là. Numéro suivant !',
    fictive: false,
  },
  {
    id: 'vo.bene.hub.04',
    voice: 'bene',
    file: 'vo/bene/bene.hub.04.webm',
    subtitle: 'J’ai archivé ta victoire. Classement : rare. Sous-classement : à renouveler.',
    fictive: false,
  },
  {
    id: 'vo.bene.hub.05',
    voice: 'bene',
    file: 'vo/bene/bene.hub.05.webm',
    subtitle: 'Tant que j’ai un tampon, il y a un guichet.',
    fictive: false,
  },
  {
    id: 'vo.bene.radio.01',
    voice: 'bene',
    file: 'vo/bene/bene.radio.01.webm',
    subtitle: 'File d’attente ouverte. Ils patienteront.',
    fictive: false,
  },
  {
    id: 'vo.josiane.hub.01',
    voice: 'josiane',
    file: 'vo/josiane/josiane.hub.01.webm',
    subtitle: 'Ta dotation, je la range. Ce qui est réformé, je le réforme. Proprement.',
    fictive: false,
  },
  {
    id: 'vo.josiane.hub.02',
    voice: 'josiane',
    file: 'vo/josiane/josiane.hub.02.webm',
    subtitle: 'Le mannequin, là. Tape dedans, il ne porte pas plainte.',
    fictive: false,
  },
  {
    id: 'vo.josiane.hub.03',
    voice: 'josiane',
    file: 'vo/josiane/josiane.hub.03.webm',
    subtitle:
      'Tu ne m’appelles jamais, à la radio. Ça, c’est pas dans le règlement, mais c’est dans le cœur.',
    fictive: false,
  },
  {
    id: 'vo.josiane.hub.04',
    voice: 'josiane',
    file: 'vo/josiane/josiane.hub.04.webm',
    subtitle: 'Mon sanglier de deux mille neuf était plus coriace. Mais bravo, hein.',
    fictive: false,
  },
  {
    id: 'vo.josiane.radio.01',
    voice: 'josiane',
    file: 'vo/josiane/josiane.radio.01.webm',
    subtitle: 'Ces quatorze-là, ils ont un nom.',
    fictive: false,
  },
  {
    id: 'vo.josiane.hub.05',
    voice: 'josiane',
    file: 'vo/josiane/josiane.hub.05.webm',
    subtitle: 'Je contrôle les billets. Ce soir, je contrôle un contrat.',
    fictive: false,
  },
  {
    id: 'vo.josiane.radio.02',
    voice: 'josiane',
    file: 'vo/josiane/josiane.radio.02.webm',
    subtitle: 'Titre non valable. Renvoie-leur.',
    fictive: false,
  },
  {
    id: 'vo.invite.boss.01',
    voice: 'invite',
    file: 'vo/invite/invite.boss.01.webm',
    subtitle: 'Mesdames, messieurs, chers amis… et vous, au fond, en gilet orange.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.02',
    voice: 'invite',
    file: 'vo/invite/invite.boss.02.webm',
    subtitle:
      'Nous sommes ici pour inaugurer l’avenir. Et l’avenir, je le dis souvent, ça s’inaugure.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.03',
    voice: 'invite',
    file: 'vo/invite/invite.boss.03.webm',
    subtitle: 'Je vois que l’émotion vous gagne. Page deux.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.04',
    voice: 'invite',
    file: 'vo/invite/invite.boss.04.webm',
    subtitle: 'Je serai bref.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.05',
    voice: 'invite',
    file: 'vo/invite/invite.boss.05.webm',
    subtitle: 'Permettez-moi une parenthèse. Elle durera le temps qu’il faudra.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.06',
    voice: 'invite',
    file: 'vo/invite/invite.boss.06.webm',
    subtitle: 'Et j’ajouterai…',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.07',
    voice: 'invite',
    file: 'vo/invite/invite.boss.07.webm',
    subtitle: 'Cette pierre est la première d’une longue série.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.08',
    voice: 'invite',
    file: 'vo/invite/invite.boss.08.webm',
    subtitle: 'Les travaux commenceront… bientôt. C’est un engagement.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.09',
    voice: 'invite',
    file: 'vo/invite/invite.boss.09.webm',
    subtitle: 'Un ruban, c’est une promesse. Celle-là, je la coupe.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.10',
    voice: 'invite',
    file: 'vo/invite/invite.boss.10.webm',
    subtitle: 'Mons mérite mieux !',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.11',
    voice: 'invite',
    file: 'vo/invite/invite.boss.11.webm',
    subtitle: 'Une concertation ? Excellente idée. Je note… je note.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.12',
    voice: 'invite',
    file: 'vo/invite/invite.boss.12.webm',
    subtitle: '… On m’avait parlé d’une inauguration.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.13',
    voice: 'invite',
    file: 'vo/invite/invite.boss.13.webm',
    subtitle: 'Je n’inaugure pas une vente à la découpe.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.14',
    voice: 'invite',
    file: 'vo/invite/invite.boss.14.webm',
    subtitle: 'Il doit bien y avoir, quelque part dans cette ville, quelque chose qui ouvre.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.15',
    voice: 'invite',
    file: 'vo/invite/invite.boss.15.webm',
    subtitle:
      'Je déclare ce Shift… clos. Applaudissez, applaudissez. Et rendez-vous à la prochaine inauguration.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.16',
    voice: 'invite',
    file: 'vo/invite/invite.boss.16.webm',
    subtitle: 'Encore vous ? Je n’avais prévu qu’un seul ruban.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.17',
    voice: 'invite',
    file: 'vo/invite/invite.boss.17.webm',
    subtitle: 'J’ai raccourci le discours. Trente-neuf pages.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.18',
    voice: 'invite',
    file: 'vo/invite/invite.boss.18.webm',
    subtitle: 'Vous savez, à Mons, on inaugure même les reports.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.19',
    voice: 'invite',
    file: 'vo/invite/invite.boss.19.webm',
    subtitle: 'Merci, merci… gardez-en pour la fin.',
    fictive: true,
  },
  {
    id: 'vo.invite.boss.20',
    voice: 'invite',
    file: 'vo/invite/invite.boss.20.webm',
    subtitle: 'Je coupe !',
    fictive: true,
  },
  {
    id: 'vo.lurcke.boss.01',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.01.webm',
    subtitle:
      'Ah. L’équipe terrain. Entrez. Un café ? La machine fait quarante-sept recettes. Personne ne sait l’allumer.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.02',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.02.webm',
    subtitle:
      'Arrêter ? On ne fait que libérer le marché. Et pour un sept heures douze qui transporte quatorze personnes ? Quatorze ! Ce n’est même pas un chiffre significatif.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.03',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.03.webm',
    subtitle:
      'Pas dans le tableur. Je lance la présentation. Quatre cent douze slides. Il n’y a pas de pause prévue.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.04',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.04.webm',
    subtitle: 'C’est agile.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.05',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.05.webm',
    subtitle:
      'Léon, Léon, Léon… Je ne libéralise pas un réseau avec un incident voyageur en cours, ça fait mauvais genre dans le reporting. Posez cette clé, on va faire un petit atelier.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.06',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.06.webm',
    subtitle: 'Encore vous ? J’ai pourtant envoyé un Sondage.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.07',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.07.webm',
    subtitle: 'Cette fois, j’ai prévu une pause. Pour moi.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.08',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.08.webm',
    subtitle: 'J’ai benchmarké votre clé. Au Japon, ils utilisent des tablettes.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.09',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.09.webm',
    subtitle: 'Je n’ai plus de slides. J’ai fait les quatre cent douze. Il ne reste que moi.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.10',
    voice: 'lurcke',
    file: null,
    subtitle: 'Slide un sur quatre cent douze. Restez concentrés, c’est la plus courte.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.11',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.11.webm',
    subtitle: 'Benchmark international ! Au Japon, ça marche !',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.12',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.12.webm',
    subtitle: 'Je vous mets en copie. Et vous. Et vous.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.13',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.13.webm',
    subtitle: 'Slide trois cents : le réseau, en lots. C’est plus lisible, non ?',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.14',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.14.webm',
    subtitle: 'Mesdames et messieurs du Conseil, vous m’entendez ? … Vous êtes en mute.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.15',
    voice: 'lurcke',
    file: null,
    subtitle:
      'Article premier : le personnel est un actif variable. Article deux : l’article premier n’est pas négociable !',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.16',
    voice: 'lurcke',
    file: null,
    subtitle: 'Slide quarante-sept : ce n’est pas la mienne…',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.17',
    voice: 'lurcke',
    file: null,
    subtitle: 'Si je ne peux pas vous convaincre, je vais vous dupliquer.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.18',
    voice: 'lurcke',
    file: null,
    subtitle: 'Recto. Verso. Recto. Verso. Sans pause.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.19',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.19.webm',
    subtitle: 'Le seul train rentable, c’est celui qui ne part pas !',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.20',
    voice: 'lurcke',
    file: null,
    subtitle: '… Concrètement ? Concrètement… je n’ai pas de slide pour ça.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.21',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.21.webm',
    subtitle: 'Bon. Soyons adultes. Une phase pilote. Une seule ligne.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.22',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.22.webm',
    subtitle: 'Mon oreillette… n’a plus de réseau.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.23',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.23.webm',
    subtitle: 'Le planning est validé. Le diaporama est validé. Même le traiteur est validé !',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.24',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.24.webm',
    subtitle: '… Ah. On me signale un conflit d’agenda. On reprogramme.',
    fictive: false,
  },
  {
    id: 'vo.lurcke.boss.25',
    voice: 'lurcke',
    file: 'vo/lurcke/lurcke.boss.25.webm',
    subtitle:
      'Félicitations, le marché est ouvert. Votre poste aussi. Votre badge vous sera envoyé par Sondage.',
    fictive: false,
  },
];
